ata <- read.csv2("hpc.txt", stringsAsFactors = FALSE)
data$Combi_date <- as.POSIXct(paste(data$Date,data$Time), format="%d/%m/%Y %H:%M:%S")
data$Global_active_power <- as.numeric(data$Global_active_power)
sub<- subset(data,data$Combi_date>="2007/02/01 00:00:00" & data$Combi_dat<"2007/02/03 00:00:00")

png("Plot3.png")
plot(x=sub$Combi_date,y=sub$Sub_metering_1,ylab = "Energy sub metering",type = "l",xlab="")
lines(x=sub$Combi_date,y=sub$Sub_metering_2,ylab = "Energy sub metering",type = "l",xlab="", col = "red")
lines(x=sub$Combi_date,y=sub$Sub_metering_3,ylab = "Energy sub metering",type = "l",xlab="", col = "blue")
dev.off()